# Generated by Django 5.1.2 on 2024-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_clase_7', '0002_compra_fruta_delete_producto_compra_fruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
