# Generated by Django 5.0.3 on 2024-10-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_clase_7', '0005_notificacion_preferenciasnotificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
    ]
