# Generated by Django 5.1.2 on 2024-10-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_clase_7', '0003_fruta_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='fruta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='fruta',
            name='categorias',
            field=models.ManyToManyField(to='aplicacion_clase_7.categoria'),
        ),
    ]
